VC-4242: added tables for banking module
overgold/bdjuno pull request #13
Opened 2022-03-26 16:19 UTC by at-kh

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-03-28 04:54 UTC, IamStubborN requested changes

2022-03-28 04:54 UTC, IamStubborN commented on database/schema/13-banking.sql
> +CREATE TABLE IF NOT EXISTS vipcoin_chain_banking_banking (
```suggestion
CREATE TABLE IF NOT EXISTS vipcoin_chain_banking_transfers (
```

2022-03-28 04:54 UTC, IamStubborN commented on database/schema/13-banking.sql
> +    kind                INT,                                    -- banking amount
```suggestion
    kind                INT,                                    -- banking kind
```

2022-03-28 04:54 UTC, IamStubborN commented on database/schema/13-banking.sql
> +);
not need, we have 'extras' JSONB at every struct

2022-03-28 04:54 UTC, IamStubborN commented on database/schema/13-banking.sql
> +);
```sql
CREATE TABLE IF NOT EXISTS vipcoin_chain_banking_reward_manager_address (
    address            TEXT NOT NULL                        -- banking address
);
```

add table please, current state of `reward_manager_address` and `set_reward_manager_address` table - will be a history

2022-03-29 11:09 UTC, PavelVlasenkoGo commented
LGTM

2022-03-29 16:46 UTC, IamStubborN commented
LGTM

2022-03-29 16:47 UTC, IamStubborN approved these changes

2022-03-30 07:59 UTC, merged