VC-4233: Create db schema assets
overgold/bdjuno pull request #19
Opened 2022-03-29 13:13 UTC by vovan1983

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-03-29 14:15 UTC, IamStubborN requested changes

2022-03-29 14:15 UTC, IamStubborN commented on database/schema/13-assets.sql
> +);
format please

2022-03-29 14:15 UTC, IamStubborN commented on database/schema/13-assets.sql
> +    policies        JSONB,									-- assets policies
INT[]

2022-03-29 14:15 UTC, IamStubborN commented on database/schema/13-assets.sql
> +   properties  	    JSONB,								   -- manage assets properties
INT[]

2022-03-29 14:15 UTC, IamStubborN commented on database/schema/13-assets.sql
> +   policies    	    JSONB,									-- create assets policies
INT[]

2022-03-29 14:24 UTC, alex-bodnar requested changes

2022-03-29 14:24 UTC, alex-bodnar commented on database/schema/13-assets.sql
> +    name		    TEXT        NOT NULL,                  -- set extra name
Замени табы на пробелы.

2022-03-29 14:24 UTC, alex-bodnar commented on database/schema/13-assets.sql
> +    issuer          TEXT        NOT NULL,					-- assets issuer
PRIMARY KEY ?

2022-03-29 14:24 UTC, alex-bodnar commented on database/schema/13-assets.sql
> +    policies        JSONB,									-- assets policies
Зачем JSONB если это масив int32?
Замени на INT[]

2022-03-29 14:24 UTC, alex-bodnar commented on database/schema/13-assets.sql
> +    properties      JSONB,									-- assets properties
Тоже не вижу смысла использовать JSONB, там 2 поля в этой структуре, лучше их добавить

2022-03-29 15:55 UTC, alex-bodnar commented on database/schema/13-assets.sql
> +    properties     INT[],         -- manage assets properties
Не INT[]
Либо:
precision   INT
fee_percent INT
Либо
properties     JSONB

2022-03-29 15:56 UTC, alex-bodnar commented on database/schema/13-assets.sql
> +    policies       JSONB,         -- manage assets policies
INT[]

2022-03-29 16:48 UTC, IamStubborN commented on database/schema/13-assets.sql
> +    properties     INT[],         -- manage assets properties
precision INT
fee_percent INT

2022-03-29 16:49 UTC, IamStubborN commented on database/schema/13-assets.sql
> +    properties JSONB,         -- create assets properties
precision INT
fee_percent INT

2022-03-29 17:25 UTC, IamStubborN commented
Нужно сквош коммитов сделать, сейчас их два одинаковых

2022-03-30 06:47 UTC, alex-bodnar approved these changes
LGTM

2022-03-30 08:55 UTC, IamStubborN commented
LGTM

2022-03-30 08:55 UTC, IamStubborN approved these changes

2022-03-30 08:56 UTC, merged