VC-4220 processing create account
overgold/bdjuno pull request #27
Opened 2022-03-31 15:26 UTC by alex-bodnar

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-03-31 21:45 UTC, NikKi-NailZ commented on _tests/database/accounts/create_account_test.go
> +}
add new line pleae

2022-03-31 21:46 UTC, NikKi-NailZ commented on database/vipcoin/chain/accounts/create_account.go
> +}
add new line please

2022-03-31 21:52 UTC, nikkibuster commented on database/vipcoin/chain/accounts/create_account.go
> +	if _, err := r.db.NamedExec(query, toCreateAccountsDatabase(msg...)); err != nil {
this may not worked if msg will be more than one, if need to add this will not work if you pass multiple records. If you need to write several rows, you should use transactions

2022-04-01 11:20 UTC, IamStubborN requested changes
LGTM

2022-04-01 11:20 UTC, IamStubborN approved these changes

2022-04-01 12:10 UTC, merged

2022-04-01 12:11 UTC, NikKi-NailZ commented
LGTM