VC-4213 add processing register user
overgold/bdjuno pull request #9
Opened 2022-03-25 11:18 UTC by alex-bodnar

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-03-25 13:26 UTC, PavelVlasenkoGo commented
LGTM

2022-03-28 04:33 UTC, IamStubborN requested changes

2022-03-28 04:33 UTC, IamStubborN commented on modules/vipcoin/chain/accounts/handle_msg.go
> +		Wallets:   []string{msg.HolderWallet},
ref_reward_wallet must be here too

2022-03-28 04:33 UTC, IamStubborN commented on modules/vipcoin/chain/accounts/handle_msg.go
> +		// return sdkerrors.Wrap(sdkerrors.ErrUnknownRequest, errMsg)
debug info?

2022-03-28 04:33 UTC, IamStubborN commented on _tests/database/accounts/register-user_test.go
> +	// db, err := sqlx.Connect("pgx", "host=10.10.1.79 port=5432 user=postgres dbname=juno password=postgres sslmode=disable")
remove

2022-03-28 06:47 UTC, alex-bodnar commented on modules/vipcoin/chain/accounts/handle_msg.go
> +		// return sdkerrors.Wrap(sdkerrors.ErrUnknownRequest, errMsg)
Будет возвращаться ошибка когда сделаем обработчики для всех сообщений, пока, что бы error-ы не сыпались - закоментировал

2022-03-28 07:26 UTC, IamStubborN approved these changes
Lgtm

2022-03-28 07:30 UTC, merged